[bumpversion]
current_version = "3.0.0a1"
commit = true
tag = true
tag_name = "v{new_version}"

[[bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[bumpversion.files]]
filename = ".env"
search = 'IMAGE_TAG={current_version}'
replace = 'IMAGE_TAG={new_version}'

[[bumpversion.files]]
filename = "Dockerfile"
search = 'IMAGE_TAG="{current_version}"'
replace = 'IMAGE_TAG="{new_version}"'
