apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ump.fullname" . }}
  labels:
    {{- include "ump.labels" . | nindent 4 }}
spec:
  # replicasets are retained for rollback purposes
  revisionHistoryLimit: 3  # Retain only the last 3 ReplicaSets
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ump.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ump.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ump.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: providers-volume
              mountPath: {{ .Values.config.providersFileMountPath | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "ump.fullname" . }}-settings
            # if auth secret is not referenced, it will be created
            {{- if not .Values.auth.existingSecret.name }}
            - secretRef:
                name: {{ include "ump.fullname" . }}-oidc-connection
            {{- end }}
          env:
            - name: UMP_CORS_ORIGINS
              value: {{ .Values.allowedOrigins.hosts | toJson | quote }}
            {{- if .Values.postgresConnection.enabled }}
            # postgres connection
            - name: UMP_JOB_STORE
              value: "postgres"
            {{- if .Values.postgresConnection.databaseUrl }}
            - name: UMP_DATABASE_URL
              value: {{ .Values.postgresConnection.databaseUrl | quote }}
            {{- end }}
            {{- if .Values.postgresConnection.existingSecret.name }}
            - name: UMP_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresConnection.existingSecret.name }}
                  key: dbname
            - name: UMP_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresConnection.existingSecret.name }}
                  key: host
            - name: UMP_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresConnection.existingSecret.name }}
                  key: port
            - name: UMP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresConnection.existingSecret.name }}
                  key: user
            - name: UMP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresConnection.existingSecret.name }}
                  key: password
            {{- end }}
            {{- end }}
            {{- if .Values.auth.existingSecret.name }}
            - name: UMP_JWKS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret.name }}
                  key: UMP_JWKS_URL
            - name: UMP_JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret.name }}
                  key: UMP_JWT_ISSUER
            - name: UMP_JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret.name }}
                  key: UMP_JWT_AUDIENCE
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.config.readinessPath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: providers-volume
          configMap:
          {{- if not .Values.providers.existingConfigMap.name }}
            name: {{ include "ump.fullname" . }}-providers
          {{- else }}
            name: {{ .Values.providers.existingConfigMap.name }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}