{{- if not .Values.auth.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ump.fullname" . }}-oidc-connection
  labels:
    {{ include "ump.labels" . | nindent 4 }}
stringData:
  UMP_JWKS_URL: {{ .Values.auth.jwksUrl | quote }}
  UMP_JWT_ISSUER: {{ .Values.auth.jwtIssuer | quote }}
  UMP_JWT_AUDIENCE: {{ .Values.auth.jwtAudience | quote }}
{{- end -}}